import 'package:flutter/material.dart';

const navy=Color(0xFF111827), orange=Color(0xFFF97316), bg=Color(0xFFF8FAFC);
void main()=>runApp(const ProApp());

class ProApp extends StatelessWidget{const ProApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'MAHER | الصنايعي',theme:ThemeData(useMaterial3:true,colorSchemeSeed:orange,scaffoldBackgroundColor:bg,fontFamily:'Arial'),home:const ProHome());}

class ProHome extends StatefulWidget{const ProHome({super.key});@override State<ProHome> createState()=>_ProHomeState();}
class _ProHomeState extends State<ProHome>{int tab=0;String job='لا يوجد عمل نشط';String selectedType='بالساعة';
final requests=[['تركيب بسكليت','بالساعة','عمّان — الجبيهة','مطلوب صنايعي لتركيب بسكليت اليوم'],['تصليح تسريب مياه','مقاولة','عمّان — خلدا','في تسريب تحت المغسلة مع حاجة لفحص كامل'],['دهان غرفة','يومي','عمّان — الصويفية','غرفة واحدة، دهان وتجهيز كامل']];
void requestDetails(List<String> r){showModalBottomSheet(context:context,isScrollControlled:true,builder:(_)=>Directionality(textDirection:TextDirection.rtl,child:Padding(padding:const EdgeInsets.all(20),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(r[0],style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('${r[1]} • ${r[2]}'),const SizedBox(height:14),Text(r[3]),const SizedBox(height:14),const Text('أرسل عرضك',style:TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:8),Row(children:[Expanded(child:TextField(keyboardType:TextInputType.number,decoration:InputDecoration(labelText:r[1]=='بالساعة'?'سعر الساعة':'السعر الإجمالي',border:const OutlineInputBorder()))),const SizedBox(width:10),FilledButton(onPressed:(){setState(()=>job='تم إرسال عرض على ${r[0]}');Navigator.pop(context);},child:const Text('إرسال العرض'))]),const SizedBox(height:20)])));}
Widget dashboard()=>ListView(padding:const EdgeInsets.all(18),children:[Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:navy,borderRadius:BorderRadius.circular(24)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('طلبات قريبة منك',style:TextStyle(color:Colors.white,fontSize:27,fontWeight:FontWeight.w900)),SizedBox(height:8),Text('اختار الطلب المناسب، أرسل سعرك، وخلي MAHER يدير باقي الرحلة.',style:TextStyle(color:Colors.white70,height:1.5))]),),const SizedBox(height:20),const Text('الطلبات الجديدة',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:10),...requests.map((r)=>Card(child:ListTile(isThreeLine:true,leading:const CircleAvatar(child:Icon(Icons.build)),title:Text(r[0],style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${r[1]}\n${r[2]}'),trailing:const Icon(Icons.chevron_left),onTap:()=>requestDetails(r)))) ,if(job!='لا يوجد عمل نشط')... [const SizedBox(height:14),Card(child:ListTile(title:const Text('حالتك الحالية',style:TextStyle(fontWeight:FontWeight.w900)),subtitle:Text(job)))] ]);
Widget active()=>ListView(padding:const EdgeInsets.all(18),children:[const Text('العمل الحالي',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:14),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const ListTile(contentPadding:EdgeInsets.zero,leading:CircleAvatar(child:Icon(Icons.person)),title:Text('العميل'),subtitle:Text('عمّان • تفاصيل العميل تظهر بعد قبول العرض')),const Divider(),Text(job,style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:14),Wrap(spacing:8,runSpacing:8,children:[FilledButton.icon(onPressed:()=>setState(()=>job='تم الوصول للعميل'),icon:const Icon(Icons.location_on),label:const Text('وصلت')),OutlinedButton.icon(onPressed:()=>setState(()=>job='تم إنهاء العمل'),icon:const Icon(Icons.check),label:const Text('إنهاء العمل'))])])))]);
Widget profile()=>ListView(padding:const EdgeInsets.all(18),children:[const Text('حساب الصنايعي',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:14),const Card(child:ListTile(leading:CircleAvatar(child:Icon(Icons.person)),title:Text('محمد — صنايعي تجريبي'),subtitle:Text('★ 4.9 • 128 طلب مكتمل'))),const SizedBox(height:8),const Card(child:Column(children:[ListTile(leading:Icon(Icons.verified_outlined),title:Text('الهوية والمهارات الموثقة')),ListTile(leading:Icon(Icons.photo_library_outlined),title:Text('معرض الأعمال')),ListTile(leading:Icon(Icons.account_balance_wallet_outlined),title:Text('الأرباح والسحوبات')),ListTile(leading:Icon(Icons.location_on_outlined),title:Text('مناطق العمل'))]))]);
@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('MAHER | الصنايعي',style:TextStyle(fontWeight:FontWeight.w900)),actions:[IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none))]),body:tab==0?dashboard():tab==1?active():profile(),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const[NavigationDestination(icon:Icon(Icons.inbox_outlined),selectedIcon:Icon(Icons.inbox),label:'الطلبات'),NavigationDestination(icon:Icon(Icons.work_outline),selectedIcon:Icon(Icons.work),label:'شغلي'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'حسابي')]));}
