import 'package:flutter/material.dart';

const navy=Color(0xFF111827), orange=Color(0xFFF97316), bg=Color(0xFFF8FAFC);
void main()=>runApp(const AdminApp());
class AdminApp extends StatelessWidget{const AdminApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'MAHER Admin',theme:ThemeData(useMaterial3:true,colorSchemeSeed:orange,scaffoldBackgroundColor:bg,fontFamily:'Arial'),home:const AdminHome());}
class AdminHome extends StatefulWidget{const AdminHome({super.key});@override State<AdminHome> createState()=>_AdminHomeState();}
class _AdminHomeState extends State<AdminHome>{int tab=0;final complaints=[['محمد أحمد','صنايعي','3 بلاغات','مراجعة مطلوبة'],['أحمد خالد','صنايعي','1 بلاغ','تنبيه'],['سارة علي','عميل','2 بلاغات','مراجعة']];
void action(String name,String a){showDialog(context:context,builder:(_)=>AlertDialog(title:Text(a),content:Text('تم تسجيل الإجراء على $name. يمكن ربط هذا الإجراء لاحقاً بنظام الحساب الحقيقي.'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('تم'))]));}
Widget stat(String title,String value,IconData icon)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[CircleAvatar(backgroundColor:orange.withOpacity(.12),child:Icon(icon,color:orange)),const SizedBox(width:12),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(value,style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900)),Text(title,style:const TextStyle(color:Colors.black54))])])));
Widget overview()=>ListView(padding:const EdgeInsets.all(18),children:[Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:navy,borderRadius:BorderRadius.circular(22)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('MAHER ADMIN',style:TextStyle(color:Colors.white,fontSize:26,fontWeight:FontWeight.w900)),SizedBox(height:7),Text('تحكم كامل بالطلبات، العملاء، الصنايعية، العمولات والبلاغات.',style:TextStyle(color:Colors.white70,height:1.5))]),),const SizedBox(height:16),stat('الطلبات اليوم','128',Icons.receipt_long),stat('إجمالي العملاء','2,430',Icons.people_outline),stat('الصنايعية النشطين','684',Icons.engineering_outlined),stat('إيراد العمولة','1,284 د.أ',Icons.account_balance_wallet_outlined),const SizedBox(height:14),const Text('نظام العمولة',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:8),Card(child:ListTile(leading:const Icon(Icons.percent),title:const Text('العمولة الحالية: 30%',style:TextStyle(fontWeight:FontWeight.w900)),subtitle:const Text('مثال: طلب بقيمة 10 د.أ → 3 د.أ MAHER → 7 د.أ للصنايعي'),trailing:TextButton(onPressed:()=>action('النظام','تعديل العمولة'),child:const Text('تعديل')))),]);
Widget reports()=>ListView(padding:const EdgeInsets.all(18),children:[const Text('البلاغات والمخالفات',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:12),...complaints.map((x)=>Card(child:ListTile(isThreeLine:true,leading:const CircleAvatar(child:Icon(Icons.report_outlined)),title:Text(x[0],style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${x[1]} • ${x[2]}\n${x[3]}'),trailing:PopupMenuButton<String>(onSelected:(v)=>action(x[0],v),itemBuilder:(_)=>const[PopupMenuItem(value:'تنبيه',child:Text('تنبيه')),PopupMenuItem(value:'تحذير',child:Text('تحذير')),PopupMenuItem(value:'خصم',child:Text('خصم')),PopupMenuItem(value:'حظر مؤقت',child:Text('حظر مؤقت')),PopupMenuItem(value:'حظر نهائي',child:Text('حظر نهائي'))]))),),]);
Widget users()=>ListView(padding:const EdgeInsets.all(18),children:[const Text('المستخدمون',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:12),const Card(child:ListTile(leading:CircleAvatar(child:Icon(Icons.person)),title:Text('العملاء'),subtitle:Text('2,430 حساب • إدارة ومراجعة وتجميد الحسابات'))),const Card(child:ListTile(leading:CircleAvatar(child:Icon(Icons.engineering)),title:Text('الصنايعية'),subtitle:Text('684 نشط • إدارة التحقق والمهارات والتقييمات'))),const Card(child:ListTile(leading:CircleAvatar(child:Icon(Icons.star)),title:Text('التقييمات'),subtitle:Text('متابعة التقييمات والشكاوى المرتبطة بالطلبات'))]);
Widget settings()=>ListView(padding:const EdgeInsets.all(18),children:[const Text('إعدادات النظام',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:12),const Card(child:Column(children:[ListTile(leading:Icon(Icons.category_outlined),title:Text('الفئات والخدمات')),ListTile(leading:Icon(Icons.payments_outlined),title:Text('الأسعار والعمولات')),ListTile(leading:Icon(Icons.notifications_outlined),title:Text('الإشعارات')),ListTile(leading:Icon(Icons.security_outlined),title:Text('الصلاحيات والأمان')),ListTile(leading:Icon(Icons.support_agent),title:Text('الدعم والنزاعات'))]))]);
@override Widget build(BuildContext c){final pages=[overview(),reports(),users(),settings()];return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('MAHER Admin',style:TextStyle(fontWeight:FontWeight.w900))),body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard_outlined),selectedIcon:Icon(Icons.dashboard),label:'الرئيسية'),NavigationDestination(icon:Icon(Icons.report_outlined),selectedIcon:Icon(Icons.report),label:'البلاغات'),NavigationDestination(icon:Icon(Icons.people_outline),selectedIcon:Icon(Icons.people),label:'المستخدمون'),NavigationDestination(icon:Icon(Icons.settings_outlined),selectedIcon:Icon(Icons.settings),label:'الإعدادات')]));}}
